### PR TITLE
Apply API security updates from 1.08.2021

### PR DESCRIPTION
**Pull request by s-mage**
Updates: https://developers.soundcloud.com/blog/security-updates-api
API: https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/post_oauth2_token

### CODE REVIEW

**Comment by s-mage** [comment]
sorry, I meant to create a PR in a cloned repo first

**Comment by rahul-sc** [comment]
Hello. I'm not a maintainer but happy to just accept this merge for now. 

If you're interested in being a maintainer of this, do let us know :)

**Comment by rahul-sc** [comment]
Probably also needs a gem repackage right? (ruby newb here)

**Comment by s-mage** [comment]
[right](https://guides.rubygems.org/publishing/)

*UPD*: But before that you probably want to bump the gem version ([example](https://github.com/soundcloud/soundcloud-ruby/commit/9e91ed8e085387daa41e1215442fa0e154c77c0a))

**Comment by s-mage** [comment]
> If you're interested in being a maintainer of this, do let us know :)

Yup, I can do it, as a part of gleam.io. [Related comment](https://github.com/soundcloud/api/issues/95#issuecomment-895623278)

**Pull request merged**
