### PR TITLE
#53 Fix for new httparty 0.14.0

### PR DESCRIPTION
**Pull request by moritzgloeckl**
Hi,

this is my fix for issue #53, as suggested [here](https://github.com/jnunemaker/httparty/issues/489). It seems to be working, but could use a little more testing.

Thanks!

### CODE REVIEW

**Comment by grobie** [comment]
Can you have a look at the broken tests? Do we need to update our dependencies?

**Comment by moritzgloeckl** [comment]
Which version of `httparty` is your CI using? I'm using `httparty 0.14.0` and it works on my machine...

**Comment by grobie** [comment]
It doesn't sound right if we use different gem versions. I guess we should
make sure that soundcloud-ruby explicitly defines its dependencies.

**Comment by moritzgloeckl** [comment]
Hmm, I checked and CI is using `httparty 0.14.0`. Check my edit I think the problem lies somewhere else.

**Comment by grobie** [comment]
Both response.is_a?(Hash) and response.parsed_response.is_a?(Hash) need to be handled. I fixed it on my won.

**Pull request closed without merging**
